export const horrorData = [
  {
    Title: "A Nightmare on Elm Street",
    Year: "1984",
    Rated: "R",
    Released: "16 Nov 1984",
    Runtime: "91 min",
    Genre: "Horror",
    Director: "Wes Craven",
    Writer: "Wes Craven",
    Actors: "Heather Langenkamp, Johnny Depp, Robert Englund",
    Plot: "Teenager Nancy Thompson must uncover the dark truth concealed by her parents after she and her friends become targets of the spirit of a serial killer with a bladed glove in their dreams, in which if they die, it kills them in rea...",
    Language: "English",
    Country: "United States",
    Awards: "6 wins & 6 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzFjZmM1ODgtMDBkMS00NWFlLTg2YmUtZjc3ZTgxMjE1OTI2L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "95%",
      },
      {
        Source: "Metacritic",
        Value: "76/100",
      },
    ],
    Metascore: "76",
    imdbRating: "7.4",
    imdbVotes: "250,630",
    imdbID: "tt0087800",
    Type: "movie",
    DVD: "24 Jul 2014",
    BoxOffice: "$25,624,448",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Exorcist",
    Year: "1973",
    Rated: "R",
    Released: "26 Dec 1973",
    Runtime: "122 min",
    Genre: "Horror",
    Director: "William Friedkin",
    Writer: "William Peter Blatty",
    Actors: "Ellen Burstyn, Max von Sydow, Linda Blair",
    Plot: "When a teenage girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her daughter.",
    Language: "English, Latin, Greek, French, German, Arabic, Kurdish",
    Country: "United States",
    Awards: "Won 2 Oscars. 17 wins & 18 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYWFlZGY2NDktY2ZjOS00ZWNkLTg0ZDAtZDY4MTM1ODU4ZjljXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "84%",
      },
      {
        Source: "Metacritic",
        Value: "81/100",
      },
    ],
    Metascore: "81",
    imdbRating: "8.1",
    imdbVotes: "425,553",
    imdbID: "tt0070047",
    Type: "movie",
    DVD: "24 Jul 2014",
    BoxOffice: "$233,005,644",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Grudge",
    Year: "2004",
    Rated: "PG-13",
    Released: "22 Oct 2004",
    Runtime: "91 min",
    Genre: "Horror, Mystery, Thriller",
    Director: "Takashi Shimizu",
    Writer: "Stephen Susco, Takashi Shimizu",
    Actors: "Sarah Michelle Gellar, Jason Behr, Clea DuVall",
    Plot: "An American nurse living and working in Tokyo is exposed to a mysterious supernatural curse, one that locks a person in a powerful rage before claiming their life and spreading to another victim.",
    Language: "English, Japanese",
    Country: "United States, Japan",
    Awards: "2 wins & 10 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjIxODg1Nzc3NF5BMl5BanBnXkFtZTcwMjM0MjEzMw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "40%",
      },
      {
        Source: "Metacritic",
        Value: "49/100",
      },
    ],
    Metascore: "49",
    imdbRating: "5.9",
    imdbVotes: "148,435",
    imdbID: "tt0391198",
    Type: "movie",
    DVD: "18 Jun 2013",
    BoxOffice: "$110,359,362",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Shining",
    Year: "1980",
    Rated: "R",
    Released: "13 Jun 1980",
    Runtime: "146 min",
    Genre: "Drama, Horror",
    Director: "Stanley Kubrick",
    Writer: "Stephen King, Stanley Kubrick, Diane Johnson",
    Actors: "Jack Nicholson, Shelley Duvall, Danny Lloyd",
    Plot: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
    Language: "English",
    Country: "United Kingdom, United States",
    Awards: "5 wins & 8 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "83%",
      },
      {
        Source: "Metacritic",
        Value: "66/100",
      },
    ],
    Metascore: "66",
    imdbRating: "8.4",
    imdbVotes: "1,059,208",
    imdbID: "tt0081505",
    Type: "movie",
    DVD: "15 Aug 2008",
    BoxOffice: "$45,634,352",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Ring",
    Year: "2002",
    Rated: "PG-13",
    Released: "18 Oct 2002",
    Runtime: "115 min",
    Genre: "Horror, Mystery",
    Director: "Gore Verbinski",
    Writer: "Ehren Kruger, Kôji Suzuki, Hiroshi Takahashi",
    Actors: "Naomi Watts, Martin Henderson, Brian Cox",
    Plot: "A journalist must investigate a mysterious videotape which seems to cause the death of anyone one week to the day after they view it.",
    Language: "English",
    Country: "United States, Japan",
    Awards: "14 wins & 12 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDA2NTg2NjE4Ml5BMl5BanBnXkFtZTYwMjYxMDg5._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "71%",
      },
      {
        Source: "Metacritic",
        Value: "57/100",
      },
    ],
    Metascore: "57",
    imdbRating: "7.1",
    imdbVotes: "363,013",
    imdbID: "tt0298130",
    Type: "movie",
    DVD: "04 Oct 2016",
    BoxOffice: "$129,128,133",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Nun",
    Year: "2018",
    Rated: "R",
    Released: "07 Sep 2018",
    Runtime: "96 min",
    Genre: "Horror, Mystery, Thriller",
    Director: "Corin Hardy",
    Writer: "Gary Dauberman, James Wan",
    Actors: "Demián Bichir, Taissa Farmiga, Jonas Bloquet",
    Plot: "A priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate the death of a young nun in Romania and confront a malevolent force in the form of a demonic nun.",
    Language: "English, French, Romanian, Latin",
    Country: "United States",
    Awards: "2 wins & 1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjM3NzQ5NDcxOF5BMl5BanBnXkFtZTgwNzM4MTQ5NTM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "25%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
    Metascore: "46",
    imdbRating: "5.3",
    imdbVotes: "150,621",
    imdbID: "tt5814060",
    Type: "movie",
    DVD: "20 Nov 2018",
    BoxOffice: "$117,481,222",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Last Exorcism",
    Year: "2010",
    Rated: "PG-13",
    Released: "27 Aug 2010",
    Runtime: "87 min",
    Genre: "Horror, Mystery, Thriller",
    Director: "Daniel Stamm",
    Writer: "Huck Botko, Andrew Gurland",
    Actors: "Patrick Fabian, Ashley Bell, Iris Bahr",
    Plot: "A troubled evangelical minister agrees to let his last exorcism be filmed by a documentary crew.",
    Language: "English, Latin",
    Country: "France, United States",
    Awards: "7 wins & 10 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDc4Mjk2MjA0NF5BMl5BanBnXkFtZTcwMzMyNjQ3Mw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "72%",
      },
      {
        Source: "Metacritic",
        Value: "63/100",
      },
    ],
    Metascore: "63",
    imdbRating: "5.7",
    imdbVotes: "51,084",
    imdbID: "tt1320244",
    Type: "movie",
    DVD: "04 Jan 2011",
    BoxOffice: "$41,034,350",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Conjuring",
    Year: "2013",
    Rated: "R",
    Released: "19 Jul 2013",
    Runtime: "112 min",
    Genre: "Horror, Mystery, Thriller",
    Director: "James Wan",
    Writer: "Chad Hayes, Carey W. Hayes",
    Actors: "Patrick Wilson, Vera Farmiga, Ron Livingston",
    Plot: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    Language: "English, Latin",
    Country: "United States",
    Awards: "15 wins & 22 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "86%",
      },
      {
        Source: "Metacritic",
        Value: "68/100",
      },
    ],
    Metascore: "68",
    imdbRating: "7.5",
    imdbVotes: "531,137",
    imdbID: "tt1457767",
    Type: "movie",
    DVD: "08 Oct 2013",
    BoxOffice: "$137,446,368",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];

export const comedyData = [
  {
    Title: "Happy Gilmore",
    Year: "1996",
    Rated: "PG-13",
    Released: "16 Feb 1996",
    Runtime: "92 min",
    Genre: "Comedy, Sport",
    Director: "Dennis Dugan",
    Writer: "Tim Herlihy, Adam Sandler",
    Actors: "Adam Sandler, Christopher McDonald, Julie Bowen",
    Plot: "A rejected hockey player puts his skills to the golf course to save his grandmother's house.",
    Language: "English",
    Country: "United States",
    Awards: "1 win & 4 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWI2NjliOTYtZjE1OS00YzAyLWJjYTQtYWNmZTQzMTQzNzVjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "61%",
      },
      {
        Source: "Metacritic",
        Value: "31/100",
      },
    ],
    Metascore: "31",
    imdbRating: "7.0",
    imdbVotes: "238,452",
    imdbID: "tt0116483",
    Type: "movie",
    DVD: "15 Jun 2012",
    BoxOffice: "$38,824,099",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Waterboy",
    Year: "1998",
    Rated: "PG-13",
    Released: "06 Nov 1998",
    Runtime: "90 min",
    Genre: "Comedy, Sport",
    Director: "Frank Coraci",
    Writer: "Tim Herlihy, Adam Sandler",
    Actors: "Adam Sandler, Kathy Bates, Henry Winkler",
    Plot: "A waterboy for a college football team discovers he has a unique tackling ability and becomes a member of the team.",
    Language: "English",
    Country: "United States",
    Awards: "6 wins & 6 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzJmZDZlMGItZGJhOC00Y2NjLTljNzctMDg5YmQ1NzU3NzYzL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "33%",
      },
      {
        Source: "Metacritic",
        Value: "41/100",
      },
    ],
    Metascore: "41",
    imdbRating: "6.1",
    imdbVotes: "171,789",
    imdbID: "tt0120484",
    Type: "movie",
    DVD: "08 Feb 2016",
    BoxOffice: "$161,491,646",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Billy Madison",
    Year: "1995",
    Rated: "PG-13",
    Released: "10 Feb 1995",
    Runtime: "89 min",
    Genre: "Comedy",
    Director: "Tamra Davis",
    Writer: "Tim Herlihy, Adam Sandler",
    Actors: "Adam Sandler, Darren McGavin, Bridgette Wilson-Sampras",
    Plot: "In order to inherit his fed up father's hotel empire, an immature and lazy man must repeat grades 1-12 all over again.",
    Language: "English, French, Spanish",
    Country: "United States",
    Awards: "1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzcyMjZmNjctNGNhMS00ZmQxLWFkNzQtYTIxYjVkYmU1NmNmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "40%",
      },
      {
        Source: "Metacritic",
        Value: "16/100",
      },
    ],
    Metascore: "16",
    imdbRating: "6.3",
    imdbVotes: "151,305",
    imdbID: "tt0112508",
    Type: "movie",
    DVD: "19 Apr 2016",
    BoxOffice: "$25,588,734",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Wedding Singer",
    Year: "1998",
    Rated: "PG-13",
    Released: "13 Feb 1998",
    Runtime: "97 min",
    Genre: "Comedy, Music, Romance",
    Director: "Frank Coraci",
    Writer: "Tim Herlihy",
    Actors: "Adam Sandler, Drew Barrymore, Christine Taylor",
    Plot: "Robbie, a singer, and Julia, a waitress, are both engaged, but to the wrong people. Fortune intervenes to help them discover each other.",
    Language: "English, Hebrew",
    Country: "United States",
    Awards: "5 wins & 7 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjM5YTQ0ZGYtMWExZi00MTFmLTg0YjUtZDcyMGNiYzE5MmNmL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "72%",
      },
      {
        Source: "Metacritic",
        Value: "59/100",
      },
    ],
    Metascore: "59",
    imdbRating: "6.9",
    imdbVotes: "157,414",
    imdbID: "tt0120888",
    Type: "movie",
    DVD: "01 Sep 2008",
    BoxOffice: "$80,245,725",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Big Daddy",
    Year: "1999",
    Rated: "PG-13",
    Released: "25 Jun 1999",
    Runtime: "93 min",
    Genre: "Comedy, Drama",
    Director: "Dennis Dugan",
    Writer: "Steve Franks, Tim Herlihy, Adam Sandler",
    Actors: "Adam Sandler, Joey Lauren Adams, Jon Stewart",
    Plot: "A lazy law-school grad adopts a kid to impress his girlfriend, but everything doesn't go as planned and he becomes the unlikely foster father.",
    Language: "English, Italian",
    Country: "United States",
    Awards: "8 wins & 14 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOWJmZTExZTYtZjg1Mi00ZDFmLTk3MTYtZTUwYzkzODA2M2ZmXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "39%",
      },
      {
        Source: "Metacritic",
        Value: "41/100",
      },
    ],
    Metascore: "41",
    imdbRating: "6.4",
    imdbVotes: "226,785",
    imdbID: "tt0142342",
    Type: "movie",
    DVD: "16 Apr 2012",
    BoxOffice: "$163,479,795",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Grown Ups",
    Year: "2010",
    Rated: "PG-13",
    Released: "25 Jun 2010",
    Runtime: "102 min",
    Genre: "Comedy",
    Director: "Dennis Dugan",
    Writer: "Adam Sandler, Fred Wolf",
    Actors: "Adam Sandler, Salma Hayek, Kevin James",
    Plot: "After their high school basketball coach passes away, five good friends and former teammates reunite for a Fourth of July holiday weekend.",
    Language: "English, Spanish",
    Country: "United States",
    Awards: "3 wins & 4 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjA0ODYwNzU5Nl5BMl5BanBnXkFtZTcwNTI1MTgxMw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "10%",
      },
      {
        Source: "Metacritic",
        Value: "30/100",
      },
    ],
    Metascore: "30",
    imdbRating: "5.9",
    imdbVotes: "263,617",
    imdbID: "tt1375670",
    Type: "movie",
    DVD: "16 Apr 2012",
    BoxOffice: "$162,001,186",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Grown Ups 2",
    Year: "2013",
    Rated: "PG-13",
    Released: "12 Jul 2013",
    Runtime: "101 min",
    Genre: "Comedy",
    Director: "Dennis Dugan",
    Writer: "Fred Wolf, Adam Sandler, Tim Herlihy",
    Actors: "Adam Sandler, Kevin James, Chris Rock",
    Plot: "After moving his family back to his hometown to be with his friends and their kids, Lenny finds out that between old bullies, new bullies, schizo bus drivers, drunk cops on skis, and four hundred costumed party crashers sometimes ...",
    Language: "English, Spanish, Ukrainian",
    Country: "United States",
    Awards: "5 wins & 15 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNTZkZDhjZTEtZjA5MC00MDU2LTk3NDItNzA2YzQ4Y2Q5NjZhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "8%",
      },
      {
        Source: "Metacritic",
        Value: "19/100",
      },
    ],
    Metascore: "19",
    imdbRating: "5.3",
    imdbVotes: "162,806",
    imdbID: "tt2191701",
    Type: "movie",
    DVD: "05 Nov 2013",
    BoxOffice: "$133,668,525",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Click",
    Year: "2006",
    Rated: "PG-13",
    Released: "23 Jun 2006",
    Runtime: "107 min",
    Genre: "Comedy, Drama, Fantasy",
    Director: "Frank Coraci",
    Writer: "Steve Koren, Mark O'Keefe",
    Actors: "Adam Sandler, Kate Beckinsale, Christopher Walken",
    Plot: "A workaholic architect finds a universal remote that allows him to fast-forward and rewind to different parts of his life. Complications arise when the remote starts to overrule his choices.",
    Language: "English, Portuguese, Japanese",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 3 wins & 12 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTA1MTUxNDY4NzReQTJeQWpwZ15BbWU2MDE3ODAxNw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "34%",
      },
      {
        Source: "Metacritic",
        Value: "45/100",
      },
    ],
    Metascore: "45",
    imdbRating: "6.4",
    imdbVotes: "344,791",
    imdbID: "tt0389860",
    Type: "movie",
    DVD: "01 Apr 2009",
    BoxOffice: "$137,355,633",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Mr. Deeds",
    Year: "2002",
    Rated: "PG-13",
    Released: "28 Jun 2002",
    Runtime: "96 min",
    Genre: "Comedy, Romance",
    Director: "Steven Brill",
    Writer: "Clarence Budington Kelland, Robert Riskin, Tim Herlihy",
    Actors: "Adam Sandler, Winona Ryder, John Turturro",
    Plot: "A sweet-natured, small-town guy inherits a controlling stake in a media conglomerate and begins to do business his way.",
    Language: "English",
    Country: "United States",
    Awards: "5 wins & 9 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTU3NTE3M2QtNWQ0MS00ZmRkLWIwNTMtOTA0ZGM5N2UwMWNjL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "22%",
      },
      {
        Source: "Metacritic",
        Value: "24/100",
      },
    ],
    Metascore: "24",
    imdbRating: "5.8",
    imdbVotes: "148,969",
    imdbID: "tt0280590",
    Type: "movie",
    DVD: "16 Apr 2012",
    BoxOffice: "$126,293,452",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Anger Management",
    Year: "2003",
    Rated: "PG-13",
    Released: "11 Apr 2003",
    Runtime: "106 min",
    Genre: "Comedy",
    Director: "Peter Segal",
    Writer: "David Dorfman",
    Actors: "Jack Nicholson, Adam Sandler, Marisa Tomei",
    Plot: "Dave Buznik is a businessman who is wrongly sentenced to an anger management program, where he meets an aggressive instructor.",
    Language: "English",
    Country: "United States",
    Awards: "2 wins & 4 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDg1YTNiODItZGYyOC00NGIwLWI3MjYtMTY3NDQ0ZDIwYjBiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.2/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "42%",
      },
      {
        Source: "Metacritic",
        Value: "52/100",
      },
    ],
    Metascore: "52",
    imdbRating: "6.2",
    imdbVotes: "223,026",
    imdbID: "tt0305224",
    Type: "movie",
    DVD: "13 May 2014",
    BoxOffice: "$135,645,823",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Longest Yard",
    Year: "2005",
    Rated: "PG-13",
    Released: "27 May 2005",
    Runtime: "113 min",
    Genre: "Comedy, Crime, Sport",
    Director: "Peter Segal",
    Writer: "Albert S. Ruddy, Tracy Keenan Wynn, Sheldon Turner",
    Actors: "Adam Sandler, Burt Reynolds, Chris Rock",
    Plot: "Prison inmates form a football team to challenge the prison guards.",
    Language: "English",
    Country: "United States",
    Awards: "3 wins & 17 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc1NTQyNDk2NV5BMl5BanBnXkFtZTcwOTE2OTQzMw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "31%",
      },
      {
        Source: "Metacritic",
        Value: "48/100",
      },
    ],
    Metascore: "48",
    imdbRating: "6.4",
    imdbVotes: "188,142",
    imdbID: "tt0398165",
    Type: "movie",
    DVD: "20 Sep 2005",
    BoxOffice: "$158,119,460",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "You Don't Mess with the Zohan",
    Year: "2008",
    Rated: "PG-13",
    Released: "06 Jun 2008",
    Runtime: "113 min",
    Genre: "Action, Comedy",
    Director: "Dennis Dugan",
    Writer: "Adam Sandler, Robert Smigel, Judd Apatow",
    Actors: "Adam Sandler, John Turturro, Emmanuelle Chriqui",
    Plot: "An Israeli Special Forces Soldier fakes his death so he can re-emerge in New York City as a hair stylist.",
    Language: "English, Hebrew",
    Country: "United States",
    Awards: "2 wins & 2 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzE2MzEzNDc5M15BMl5BanBnXkFtZTcwMzYxOTA3MQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.6/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "37%",
      },
      {
        Source: "Metacritic",
        Value: "54/100",
      },
    ],
    Metascore: "54",
    imdbRating: "5.6",
    imdbVotes: "208,893",
    imdbID: "tt0960144",
    Type: "movie",
    DVD: "16 Apr 2012",
    BoxOffice: "$100,018,837",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Blended",
    Year: "2014",
    Rated: "PG-13",
    Released: "23 May 2014",
    Runtime: "117 min",
    Genre: "Comedy, Romance",
    Director: "Frank Coraci",
    Writer: "Ivan Menchell, Clare Sera",
    Actors: "Adam Sandler, Drew Barrymore, Wendi McLendon-Covey",
    Plot: "After a bad blind date, a man and woman find themselves stuck together at a resort for families, where their attraction grows as their respective kids benefit from the burgeoning relationship.",
    Language: "English",
    Country: "United States",
    Awards: "1 win & 10 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzc2ODI5NjAyMl5BMl5BanBnXkFtZTgwMzIyOTE4MDE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "15%",
      },
      {
        Source: "Metacritic",
        Value: "31/100",
      },
    ],
    Metascore: "31",
    imdbRating: "6.5",
    imdbVotes: "138,956",
    imdbID: "tt1086772",
    Type: "movie",
    DVD: "20 Jan 2016",
    BoxOffice: "$46,306,208",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];

export const animatedData = [
  {
    Title: "Up",
    Year: "2009",
    Rated: "PG",
    Released: "29 May 2009",
    Runtime: "96 min",
    Genre: "Animation, Adventure, Comedy",
    Director: "Pete Docter, Bob Peterson",
    Writer: "Pete Docter, Bob Peterson, Tom McCarthy",
    Actors: "Edward Asner, Jordan Nagai, John Ratzenberger",
    Plot: "78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.",
    Language: "English",
    Country: "United States, Japan",
    Awards: "Won 2 Oscars. 80 wins & 87 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjBkM2RjMzItM2M3Ni00N2NjLWE3NzMtMGY4MzE4MDAzMTRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "98%",
      },
      {
        Source: "Metacritic",
        Value: "88/100",
      },
    ],
    Metascore: "88",
    imdbRating: "8.3",
    imdbVotes: "1,080,506",
    imdbID: "tt1049413",
    Type: "movie",
    DVD: "01 Jan 2014",
    BoxOffice: "$293,004,164",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Nightmare Before Christmas",
    Year: "1993",
    Rated: "PG",
    Released: "29 Oct 1993",
    Runtime: "76 min",
    Genre: "Animation, Family, Fantasy",
    Director: "Henry Selick",
    Writer: "Tim Burton, Michael McDowell, Caroline Thompson",
    Actors: "Danny Elfman, Chris Sarandon, Catherine O'Hara",
    Plot: "Jack Skellington, king of Halloween Town, discovers Christmas Town, but his attempts to bring Christmas to his home causes confusion.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 6 wins & 17 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNWE4OTNiM2ItMjY4Ni00ZTViLWFiZmEtZGEyNGY2ZmNlMzIyXkEyXkFqcGdeQXVyMDU5NDcxNw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "95%",
      },
      {
        Source: "Metacritic",
        Value: "82/100",
      },
    ],
    Metascore: "82",
    imdbRating: "7.9",
    imdbVotes: "354,537",
    imdbID: "tt0107688",
    Type: "movie",
    DVD: "01 Jan 2014",
    BoxOffice: "$77,368,668",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Coraline",
    Year: "2009",
    Rated: "PG",
    Released: "06 Feb 2009",
    Runtime: "100 min",
    Genre: "Animation, Drama, Family",
    Director: "Henry Selick",
    Writer: "Henry Selick, Neil Gaiman",
    Actors: "Dakota Fanning, Teri Hatcher, John Hodgman",
    Plot: "An adventurous 11-year-old girl finds another world that is a strangely idealized version of her frustrating home, but it has sinister secrets.",
    Language: "English, Russian",
    Country: "United States, Japan",
    Awards: "Nominated for 1 Oscar. 8 wins & 46 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzQxNjM5NzkxNV5BMl5BanBnXkFtZTcwMzg5NDMwMg@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "90%",
      },
      {
        Source: "Metacritic",
        Value: "80/100",
      },
    ],
    Metascore: "80",
    imdbRating: "7.7",
    imdbVotes: "246,823",
    imdbID: "tt0327597",
    Type: "movie",
    DVD: "12 Feb 2014",
    BoxOffice: "$75,286,229",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Lion King",
    Year: "1994",
    Rated: "G",
    Released: "24 Jun 1994",
    Runtime: "88 min",
    Genre: "Animation, Adventure, Drama",
    Director: "Roger Allers, Rob Minkoff",
    Writer: "Irene Mecchi, Jonathan Roberts, Linda Woolverton",
    Actors: "Matthew Broderick, Jeremy Irons, James Earl Jones",
    Plot: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    Language: "English, Swahili, Xhosa, Zulu",
    Country: "United States",
    Awards: "Won 2 Oscars. 43 wins & 35 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "93%",
      },
      {
        Source: "Metacritic",
        Value: "88/100",
      },
    ],
    Metascore: "88",
    imdbRating: "8.5",
    imdbVotes: "1,095,923",
    imdbID: "tt0110357",
    Type: "movie",
    DVD: "15 Aug 2017",
    BoxOffice: "$422,783,777",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Incredibles",
    Year: "2004",
    Rated: "PG",
    Released: "05 Nov 2004",
    Runtime: "115 min",
    Genre: "Animation, Action, Adventure",
    Director: "Brad Bird",
    Writer: "Brad Bird",
    Actors: "Craig T. Nelson, Samuel L. Jackson, Holly Hunter",
    Plot: "While trying to lead a quiet suburban life, a family of undercover superheroes are forced into action to save the world.",
    Language: "English, French, German, Italian, Portuguese, Russian",
    Country: "United States, Japan",
    Awards: "Won 2 Oscars. 69 wins & 56 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTY5OTU0OTc2NV5BMl5BanBnXkFtZTcwMzU4MDcyMQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.0/10",
      },
      {
        Source: "Metacritic",
        Value: "90/100",
      },
    ],
    Metascore: "90",
    imdbRating: "8.0",
    imdbVotes: "772,737",
    imdbID: "tt0317705",
    Type: "movie",
    DVD: "29 Mar 2005",
    BoxOffice: "$261,441,092",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Lego Movie",
    Year: "2014",
    Rated: "PG",
    Released: "07 Feb 2014",
    Runtime: "100 min",
    Genre: "Animation, Action, Adventure",
    Director: "Phil Lord, Christopher Miller",
    Writer: "Phil Lord, Christopher Miller, Dan Hageman",
    Actors: "Chris Pratt, Will Ferrell, Elizabeth Banks",
    Plot: 'An ordinary LEGO construction worker, thought to be the prophesied as "special", is recruited to join a quest to stop an evil tyrant from gluing the LEGO universe into eternal stasis.',
    Language: "English, Turkish",
    Country: "United States, Denmark, Australia",
    Awards: "Nominated for 1 Oscar. 72 wins & 67 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTg4MDk1ODExN15BMl5BanBnXkFtZTgwNzIyNjg3MDE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "96%",
      },
      {
        Source: "Metacritic",
        Value: "83/100",
      },
    ],
    Metascore: "83",
    imdbRating: "7.7",
    imdbVotes: "375,235",
    imdbID: "tt1490017",
    Type: "movie",
    DVD: "31 Oct 2015",
    BoxOffice: "$257,966,122",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Teen Titans",
    Year: "2003–2006",
    Rated: "TV-Y7-FV",
    Released: "19 Jul 2003",
    Runtime: "23 min",
    Genre: "Animation, Action, Adventure",
    Director: "N/A",
    Writer: "David Slack, Bob Haney, Bruno Premiani",
    Actors: "Hynden Walch, Greg Cipes, Scott Menville",
    Plot: "A team of five teenaged superheroes save the world from many villains around their city while experiencing things normal teens face today.",
    Language: "English, Spanish, French",
    Country: "United States",
    Awards: "4 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2E5ZjM1MzItYzFjZC00YzYyLWFmZjgtZTVhZGMzMWUwNDcyXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.9/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.9",
    imdbVotes: "35,816",
    imdbID: "tt0343314",
    Type: "series",
    totalSeasons: "5",
    Response: "True",
  },
  {
    Title: "Teen Titans Go!",
    Year: "2013–",
    Rated: "TV-PG",
    Released: "23 Apr 2013",
    Runtime: "10 min",
    Genre: "Animation, Short, Action",
    Director: "N/A",
    Writer: "Michael Jelenic, Aaron Horvath",
    Actors: "Greg Cipes, Khary Payton, Scott Menville",
    Plot: "Superhero roommates Robin, Cyborg, Starfire, Raven and Beast Boy love saving the day, but what happens when they're done fighting crime?",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 3 Primetime Emmys. 4 wins & 19 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjE5MjMzOTc1Ml5BMl5BanBnXkFtZTcwNDQxMDY5OQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.5",
    imdbVotes: "23,214",
    imdbID: "tt2771780",
    Type: "series",
    totalSeasons: "8",
    Response: "True",
  },
];
